/**
 * SA4E-241 — PegaRuleChecksumStrategy tests (CHECKSUM CORRECTNESS = priority #1).
 * UT: bit-for-bit vs INDEPENDENT vectors (pega-checksum-vectors.csv, TD-1).
 * PBT: determinism + normalization + INV-1 (CSV path ≡ interpolated path).
 * Vectors' expected_sha256 was generated by a separate node script (NOT by
 * computePegaChecksum) → no tautology.
 */
import { describe, it, expect } from "vitest";
import fc from "fast-check";
import { computePegaChecksum, PegaRuleChecksumStrategy } from "../PegaRuleChecksumStrategy";
import { pegaVectors } from "./fixtures/loadFixtures";

describe("computePegaChecksum — vectors (IC-02, TD-1)", () => {
  for (const v of pegaVectors()) {
    it(`${v.id}: matches independent sha256 vector`, () => {
      const got = computePegaChecksum({
        pzInsKey: v.pzInsKey,
        pxUpdateDateTime: v.pxUpdateDateTime,
        pxSaveDateTime: v.pxSaveDateTime,
      });
      expect(got).toBe(v.expected_sha256);
    });
  }

  it("produces lowercase 64-char hex", () => {
    const h = computePegaChecksum({ pzInsKey: "RULE-A" });
    expect(h).toMatch(/^[0-9a-f]{64}$/);
  });

  it("null/undefined timestamps normalize to empty (BR-04)", () => {
    const a = computePegaChecksum({ pzInsKey: "R", pxUpdateDateTime: null, pxSaveDateTime: undefined });
    const b = computePegaChecksum({ pzInsKey: "R", pxUpdateDateTime: "", pxSaveDateTime: "" });
    expect(a).toBe(b);
  });

  it("trims each field before hashing (BR-04)", () => {
    const a = computePegaChecksum({ pzInsKey: " R ", pxUpdateDateTime: " t ", pxSaveDateTime: " s " });
    const b = computePegaChecksum({ pzInsKey: "R", pxUpdateDateTime: "t", pxSaveDateTime: "s" });
    expect(a).toBe(b);
  });
});

describe("computePegaChecksum — PBT (determinism/normalization/INV-1)", () => {
  const field = fc.string({ maxLength: 40 });

  it("PBT: deterministic — same input → same output", () => {
    fc.assert(fc.property(field, field, field, (a, b, c) => {
      const input = { pzInsKey: a, pxUpdateDateTime: b, pxSaveDateTime: c };
      expect(computePegaChecksum(input)).toBe(computePegaChecksum({ ...input }));
    }));
  });

  it("PBT: whitespace padding does not change the checksum (trim)", () => {
    fc.assert(fc.property(field, field, field, (a, b, c) => {
      const bare = computePegaChecksum({ pzInsKey: a.trim(), pxUpdateDateTime: b.trim(), pxSaveDateTime: c.trim() });
      const padded = computePegaChecksum({ pzInsKey: `  ${a.trim()} `, pxUpdateDateTime: ` ${b.trim()}  `, pxSaveDateTime: `\t${c.trim()} ` });
      expect(padded).toBe(bare);
    }));
  });

  it("PBT: null ≡ empty string for timestamps", () => {
    fc.assert(fc.property(field, (ins) => {
      const withNull = computePegaChecksum({ pzInsKey: ins, pxUpdateDateTime: null, pxSaveDateTime: null });
      const withEmpty = computePegaChecksum({ pzInsKey: ins, pxUpdateDateTime: "", pxSaveDateTime: "" });
      expect(withNull).toBe(withEmpty);
    }));
  });

  it("INV-1 (PBT): CSV-verify path ≡ interpolated path — same 3 fields → same checksum", () => {
    const strategy = new PegaRuleChecksumStrategy();
    fc.assert(fc.property(field, field, field, (a, b, c) => {
      const input = { pzInsKey: a, pxUpdateDateTime: b, pxSaveDateTime: c };
      // Source A (CSV verify) uses computePegaChecksum; Source B (interpolated)
      // uses the strategy — they MUST agree for the same rule identity.
      expect(strategy.compute(input)).toBe(computePegaChecksum(input));
    }));
  });
});
